# Generated by Django 4.2.1 on 2026-06-18 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Explain the exercise. HTML is supported.')),
                ('starter_code', models.TextField(default='# Write your code here\n', help_text='Initial code shown to user')),
                ('solution_code', models.TextField(help_text='Correct solution (only visible in admin)')),
                ('expected_output', models.TextField(help_text='Expected output to verify the solution')),
                ('hint', models.TextField(blank=True, help_text='Optional hint for the user')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='course.product')),
            ],
            options={
                'verbose_name': 'Exercise',
                'verbose_name_plural': 'Exercises',
                'ordering': ['order'],
            },
        ),
    ]
